version: '3'
services:
 database:
  container_name: r1ds_wallet_db
  image: mysql:latest
  volumes:
   - database:/var/lib/mysql
  ports:
   - "3335:3306"
  environment:
   - MYSQL_USER=wallet
   - MYSQL_PASSWORD=ASecurePwd
   - MYSQL_DATABASE=wallet_service
   - MYSQL_RANDOM_ROOT_PASSWORD=yes

 backend:
  container_name: r1ds_wallet_backend
  build: .
  ports:
   - "4574:3000"
  environment:
   - MYSQL_CONN=wallet:ASecurePwd@tcp(r1ds_wallet_db:3306)/wallet_service?charset=utf8&parseTime=true
  depends_on:
   - database

volumes:
 database:
